project:
  type: default
  output-dir: output
  render:
    - docs/01-software-development-and-operations.md
    - docs/02-building-business-data-pipelines.md
    - docs/03-building-business-analytics-solutions.md

format:
  pdf:
    number-sections: false
